export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_USERNAME = "SET_USERNAME";
export const LOADING_TOGGLE_ACTION = "LOADING_TOGGLE_ACTION";
export const SET_USERNAME_FAILED = "SET_USERNAME_FAILED";
